Repository AY2223S1-CS2103T-T13-4/tp, pull requests merged in 2022-10, with the labels that each got.

#98 Add Ui Task List panel.
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TaskListCard.java
  src/main/java/seedu/address/ui/TaskListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TaskListCard.fxml
  src/main/resources/view/TaskListPanel.fxml
Labels: priority.High

#107 Implement execute for TaskAddCommand
  src/main/java/seedu/address/logic/commands/tasks/TaskAddCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/ContactAddCommandTest.java
Labels: priority.High

#110 Update documentation
  docs/DevOps.md
  docs/index.md
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement, priority.High

#112 Add TaskBuilder
  src/test/java/taskbook/testutil/TaskBuilder.java
Labels: type.Enhancement, priority.High

#113 Implement execute for TaskDeleteCommand + unit tests
  src/main/java/taskbook/commons/core/Messages.java
  src/main/java/taskbook/logic/commands/tasks/TaskAddCommand.java
  src/main/java/taskbook/logic/commands/tasks/TaskDeleteCommand.java
  src/main/java/taskbook/model/AddressBook.java
  src/main/java/taskbook/model/Model.java
  src/main/java/taskbook/model/ModelManager.java
  src/main/java/taskbook/model/ReadOnlyAddressBook.java
  src/test/java/taskbook/logic/commands/ContactAddCommandTest.java
  src/test/java/taskbook/model/AddressBookTest.java
  src/test/java/taskbook/model/ModelManagerTest.java
Labels: priority.High

#108 Create tests for task commands
  src/main/java/taskbook/logic/commands/tasks/TaskAddCommand.java
  src/main/java/taskbook/logic/commands/tasks/TaskDeleteCommand.java
  src/main/java/taskbook/logic/parser/tasks/TaskAddCommandParser.java
  src/test/java/taskbook/logic/commands/CommandTestUtil.java
  src/test/java/taskbook/logic/commands/TaskAddCommandTest.java
  src/test/java/taskbook/logic/commands/TaskDeleteCommandTest.java
  src/test/java/taskbook/logic/parser/TaskAddCommandParserTest.java
  src/test/java/taskbook/logic/parser/TaskDeleteCommandParserTest.java
Labels: type.Task, priority.High

#117 Update task list in Ui to be the global task list
  src/main/java/taskbook/logic/Logic.java
  src/main/java/taskbook/logic/LogicManager.java
  src/main/java/taskbook/ui/MainWindow.java
Labels: priority.High

#121 Update User Guide: Task Add
  docs/UserGuide.md
Labels: priority.High

#122 Update User Guide: Fix line breaks
  docs/UserGuide.md
Labels: priority.High

#124 Add getStatus method to task
  src/main/java/taskbook/model/task/Task.java
  src/main/java/taskbook/ui/TaskListCard.java
Labels: priority.High

#123 Update readme Ui to match current project progress
  docs/images/Ui.png
Labels: priority.High

#139 Update TaskBook methods and add tests
  src/main/java/taskbook/model/TaskBook.java
  src/test/data/JsonSerializableTaskBookTest/typicalPersonsTaskBook.json
  src/test/java/taskbook/model/TaskBookTest.java
  src/test/java/taskbook/storage/JsonSerializableTaskBookTest.java
Labels: priority.High

#143 Increase size of console window size
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium

#144 Add sort command to task list.
  src/main/java/taskbook/logic/Logic.java
  src/main/java/taskbook/logic/LogicManager.java
  src/main/java/taskbook/logic/commands/tasks/TaskDeleteCommand.java
  src/main/java/taskbook/logic/commands/tasks/TaskSortAddedChronologicalCommand.java
  src/main/java/taskbook/logic/commands/tasks/TaskSortCommand.java
  src/main/java/taskbook/logic/commands/tasks/TaskSortDescriptionAlphabeticalCommand.java
  src/main/java/taskbook/logic/parser/tasks/TaskCategoryParser.java
  src/main/java/taskbook/logic/parser/tasks/TaskSortCommandParser.java
  src/main/java/taskbook/logic/parser/tasks/enums/SortTypes.java
  src/main/java/taskbook/model/Model.java
  src/main/java/taskbook/model/ModelManager.java
  src/main/java/taskbook/model/task/Description.java
  src/main/java/taskbook/model/task/Task.java
  src/main/java/taskbook/model/task/TaskList.java
  src/main/java/taskbook/ui/MainWindow.java
  src/test/java/taskbook/logic/commands/ContactAddCommandTest.java
Labels: priority.Medium

#140 Update ContactDelete, Add ContactEdit, TaskEdit
  docs/UserGuide.md
  src/main/java/taskbook/logic/commands/contacts/ContactDeleteCommand.java
  src/main/java/taskbook/logic/commands/contacts/ContactEditCommand.java
  src/main/java/taskbook/logic/commands/tasks/TaskEditCommand.java
  src/main/java/taskbook/logic/parser/contacts/ContactCategoryParser.java
  src/main/java/taskbook/logic/parser/contacts/ContactEditCommandParser.java
  src/main/java/taskbook/logic/parser/tasks/TaskCategoryParser.java
  src/main/java/taskbook/logic/parser/tasks/TaskEditCommandParser.java
  src/main/java/taskbook/model/Model.java
  src/main/java/taskbook/model/ModelManager.java
  src/main/java/taskbook/model/TaskBook.java
  src/main/java/taskbook/model/task/Deadline.java
  src/main/java/taskbook/model/task/EditTaskDescriptor.java
  src/main/java/taskbook/model/task/Event.java
  src/main/java/taskbook/model/task/Task.java
  src/main/java/taskbook/model/task/Todo.java
  src/test/data/JsonSerializableTaskBookTest/typicalPersonsTaskBook.json
  src/test/java/taskbook/logic/commands/CommandTestUtil.java
  src/test/java/taskbook/logic/commands/ContactAddCommandTest.java
  src/test/java/taskbook/logic/commands/ContactDeleteCommandTest.java
  src/test/java/taskbook/logic/commands/ContactEditCommandTest.java
  src/test/java/taskbook/logic/commands/EditPersonDescriptorTest.java
  src/test/java/taskbook/logic/commands/TaskEditCommandTest.java
  src/test/java/taskbook/logic/parser/ContactEditCommandParserTest.java
  src/test/java/taskbook/logic/parser/contacts/ContactCategoryParserTest.java
  src/test/java/taskbook/logic/parser/tasks/TaskEditCommandParserTest.java
  src/test/java/taskbook/model/ModelManagerTest.java
  src/test/java/taskbook/testutil/EditPersonDescriptorBuilder.java
  src/test/java/taskbook/testutil/EditTaskDescriptorBuilder.java
  src/test/java/taskbook/testutil/PersonUtil.java
  src/test/java/taskbook/testutil/TypicalIndexes.java
  src/test/java/taskbook/testutil/TypicalTaskBook.java
Labels: priority.High

#146 Enable run assertions
  build.gradle
Labels: priority.High

#150 Updated Task Sort command parser to match other parsers
  docs/UserGuide.md
  src/main/java/taskbook/logic/parser/CliSyntax.java
  src/main/java/taskbook/logic/parser/tasks/TaskCategoryParser.java
  src/main/java/taskbook/logic/parser/tasks/TaskSortCommandParser.java
  src/main/java/taskbook/logic/parser/tasks/enums/SortTypes.java
Labels: priority.Medium

#151 Add methods to set predicates for filtered task list
  src/main/java/taskbook/logic/commands/tasks/TaskFindCommand.java
  src/main/java/taskbook/logic/commands/tasks/TaskSortAddedChronologicalCommand.java
  src/main/java/taskbook/logic/commands/tasks/TaskSortDescriptionAlphabeticalCommand.java
  src/main/java/taskbook/model/Model.java
  src/main/java/taskbook/model/ModelManager.java
  src/test/java/taskbook/logic/commands/ContactAddCommandTest.java
Labels: priority.Medium

#145 Storage Changes for Todo/Event/Deadline
  src/main/java/taskbook/model/task/Deadline.java
  src/main/java/taskbook/model/task/Description.java
  src/main/java/taskbook/model/task/Event.java
  src/main/java/taskbook/storage/JsonAdaptedDeadline.java
  src/main/java/taskbook/storage/JsonAdaptedEvent.java
  src/main/java/taskbook/storage/JsonAdaptedTask.java
  src/main/java/taskbook/storage/JsonAdaptedTodo.java
  src/main/java/taskbook/storage/JsonSerializableTaskBook.java
  src/test/data/JsonSerializableTaskBookTest/typicalPersonsTaskBook.json
  src/test/java/taskbook/logic/commands/TaskEditCommandTest.java
  src/test/java/taskbook/model/task/DeadlineTest.java
  src/test/java/taskbook/model/task/EventTest.java
  src/test/java/taskbook/model/task/TodoTest.java
  src/test/java/taskbook/storage/JsonAdaptedTaskTest.java
  src/test/java/taskbook/testutil/DeadlineBuilder.java
  src/test/java/taskbook/testutil/EventBuilder.java
  src/test/java/taskbook/testutil/TaskBuilder.java
  src/test/java/taskbook/testutil/TodoBuilder.java
  src/test/java/taskbook/testutil/TypicalTaskBook.java
Labels: priority.High

#153 Update DG: Command History Navigation and Undo/Redo
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/NextCommandHistorySequenceDiagram.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/diagrams/tracing/LogicSequenceDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/NextCommandHistorySequenceDiagram.png
  docs/images/ParserClasses.png
  docs/images/UndoSequenceDiagram.png
  docs/images/tracing/LogicSequenceDiagram.png
Labels: priority.Medium

#154 Add command history navigation
  build.gradle
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/NextCommandHistorySequenceDiagram.puml
  docs/images/NextCommandHistorySequenceDiagram.png
  src/main/java/taskbook/logic/CommandHistory.java
  src/main/java/taskbook/logic/CommandHistoryManager.java
  src/main/java/taskbook/logic/Logic.java
  src/main/java/taskbook/logic/LogicManager.java
  src/main/java/taskbook/ui/CommandBox.java
  src/main/java/taskbook/ui/MainWindow.java
  src/test/java/taskbook/logic/CommandHistoryManagerTest.java
  src/test/java/taskbook/logic/LogicManagerTest.java
Labels: priority.Medium

#156 Fix sort command parse
  src/main/java/taskbook/logic/parser/tasks/TaskSortCommandParser.java
Labels: type.Bug

#157 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/SortDescriptionAlphabeticalSequenceDiagram
  docs/diagrams/UiClassDiagram.puml
  docs/images/SortDescriptionAlphabeticalSequenceDiagram.png
  docs/images/UiClassDiagram.png
Labels: priority.Medium

#160 Bug Fix: Duplicate task
  src/main/java/taskbook/logic/commands/tasks/TaskAddCommand.java
  src/main/java/taskbook/logic/commands/tasks/TaskDeadlineCommand.java
  src/main/java/taskbook/logic/commands/tasks/TaskEventCommand.java
  src/main/java/taskbook/logic/commands/tasks/TaskTodoCommand.java
  src/test/java/taskbook/logic/commands/TaskDeadlineCommandTest.java
  src/test/java/taskbook/logic/commands/TaskEventCommandTest.java
  src/test/java/taskbook/logic/commands/TaskTodoCommandTest.java
  src/test/java/taskbook/logic/commands/modelstubs/ModelStubAcceptingTaskAdded.java
Labels: type.Bug, severity.Medium

#159 Feature Undo & Redo
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CommandHistoryActivityDiagram.puml
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/images/CommandHistoryActivityDiagram.png
  docs/images/CommitActivityDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  src/main/java/taskbook/logic/commands/ClearCommand.java
  src/main/java/taskbook/logic/commands/categoryless/RedoCommand.java
  src/main/java/taskbook/logic/commands/categoryless/UndoCommand.java
  src/main/java/taskbook/logic/commands/contacts/ContactAddCommand.java
  src/main/java/taskbook/logic/commands/contacts/ContactDeleteCommand.java
  src/main/java/taskbook/logic/commands/contacts/ContactEditCommand.java
  src/main/java/taskbook/logic/commands/tasks/TaskDeadlineCommand.java
  src/main/java/taskbook/logic/commands/tasks/TaskDeleteCommand.java
  src/main/java/taskbook/logic/commands/tasks/TaskEditCommand.java
  src/main/java/taskbook/logic/commands/tasks/TaskEventCommand.java
  src/main/java/taskbook/logic/commands/tasks/TaskMarkCommand.java
  src/main/java/taskbook/logic/commands/tasks/TaskTodoCommand.java
  src/main/java/taskbook/logic/commands/tasks/TaskUnmarkCommand.java
  src/main/java/taskbook/logic/parser/categoryless/CategorylessParser.java
  src/main/java/taskbook/model/Model.java
  src/main/java/taskbook/model/ModelManager.java
  src/main/java/taskbook/model/TaskBook.java
  src/main/java/taskbook/model/VersionedTaskBook.java
  src/test/java/taskbook/logic/commands/RedoCommandTest.java
  src/test/java/taskbook/logic/commands/UndoCommandTest.java
  src/test/java/taskbook/logic/commands/modelstubs/ModelStub.java
  src/test/java/taskbook/model/ModelManagerTest.java
  src/test/java/taskbook/model/VersionedTaskBookTest.java
  src/test/java/taskbook/testutil/TaskBookBuilder.java
Labels: priority.Medium

#166 Add sort unit test
  src/main/java/taskbook/logic/parser/tasks/TaskSortCommandParser.java
  src/main/java/taskbook/model/ModelManager.java
  src/test/java/taskbook/logic/commands/TaskSortCommandTest.java
  src/test/java/taskbook/logic/commands/modelstubs/ModelStubAcceptingTaskAdded.java
  src/test/java/taskbook/logic/parser/TaskBookParserTest.java
  src/test/java/taskbook/logic/parser/TaskSortCommandParserTest.java
  src/test/java/taskbook/logic/parser/tasks/TaskCategoryParserTest.java
Labels: priority.Medium

#167 Add shortcut to category words contact and task
  src/main/java/taskbook/logic/parser/TaskBookParser.java
  src/main/java/taskbook/logic/parser/contacts/ContactCategoryParser.java
  src/main/java/taskbook/logic/parser/tasks/TaskCategoryParser.java
  src/test/java/taskbook/logic/parser/TaskBookParserTest.java
Labels: priority.Medium

#170 Add help command
  docs/UserGuide.md
  src/main/java/taskbook/logic/commands/HelpCommand.java
  src/main/java/taskbook/logic/commands/categoryless/ExitCommand.java
  src/main/java/taskbook/logic/commands/categoryless/HelpCommand.java
  src/main/java/taskbook/logic/commands/categoryless/RedoCommand.java
  src/main/java/taskbook/logic/commands/categoryless/UndoCommand.java
  src/main/java/taskbook/logic/commands/contacts/ContactListCommand.java
  src/main/java/taskbook/logic/commands/tasks/TaskEditCommand.java
  src/main/java/taskbook/logic/commands/tasks/TaskListCommand.java
  src/main/java/taskbook/logic/parser/CliSyntax.java
  src/main/java/taskbook/logic/parser/TaskBookParser.java
  src/main/java/taskbook/logic/parser/categoryless/CategorylessParser.java
  src/main/java/taskbook/logic/parser/categoryless/HelpCommandParser.java
  src/test/java/taskbook/logic/commands/HelpCommandTest.java
  src/test/java/taskbook/logic/parser/TaskBookParserTest.java
  src/test/java/taskbook/logic/parser/categoryless/HelpCommandParserTest.java
Labels: priority.Medium

#169 Optional phone, email and address fields for contact add
  docs/UserGuide.md
  src/main/java/taskbook/logic/parser/contacts/ContactAddCommandParser.java
  src/main/java/taskbook/model/person/Address.java
  src/main/java/taskbook/model/person/Email.java
  src/main/java/taskbook/model/person/Phone.java
  src/test/java/taskbook/logic/parser/ContactAddCommandParserTest.java
Labels: type.Task, priority.High

#161 Add task find command
  docs/UserGuide.md
  src/main/java/taskbook/logic/commands/Command.java
  src/main/java/taskbook/logic/commands/categoryless/HelpCommand.java
  src/main/java/taskbook/logic/commands/tasks/TaskFindCommand.java
  src/main/java/taskbook/logic/commands/tasks/TaskSortCommand.java
  src/main/java/taskbook/logic/parser/CliSyntax.java
  src/main/java/taskbook/logic/parser/tasks/TaskCategoryParser.java
  src/main/java/taskbook/logic/parser/tasks/TaskFindCommandParser.java
  src/main/java/taskbook/model/person/Name.java
  src/main/java/taskbook/model/task/Description.java
  src/main/java/taskbook/model/task/Task.java
  src/main/java/taskbook/model/task/enums/Assignment.java
  src/test/java/taskbook/logic/commands/TaskFindCommandTest.java
  src/test/java/taskbook/logic/parser/TaskFindCommandParserTest.java
Labels: type.Story, type.Task, priority.Medium

#171 Add contact sort command
  src/main/java/taskbook/logic/Logic.java
  src/main/java/taskbook/logic/LogicManager.java
  src/main/java/taskbook/logic/commands/FindCommand.java
  src/main/java/taskbook/logic/commands/categoryless/HelpCommand.java
  src/main/java/taskbook/logic/commands/categoryless/RedoCommand.java
  src/main/java/taskbook/logic/commands/categoryless/UndoCommand.java
  src/main/java/taskbook/logic/commands/contacts/ContactEditCommand.java
  src/main/java/taskbook/logic/commands/contacts/ContactListCommand.java
  src/main/java/taskbook/logic/commands/contacts/ContactSortAddedChronologicalCommand.java
  src/main/java/taskbook/logic/commands/contacts/ContactSortCommand.java
  src/main/java/taskbook/logic/commands/contacts/ContactSortNameAlphabeticalCommand.java
  src/main/java/taskbook/logic/commands/tasks/TaskEditCommand.java
  src/main/java/taskbook/logic/commands/tasks/TaskMarkCommand.java
  src/main/java/taskbook/logic/commands/tasks/TaskUnmarkCommand.java
  src/main/java/taskbook/logic/parser/contacts/ContactCategoryParser.java
  src/main/java/taskbook/logic/parser/contacts/ContactSortCommandParser.java
  src/main/java/taskbook/logic/parser/contacts/enums/SortTypes.java
  src/main/java/taskbook/model/Model.java
  src/main/java/taskbook/model/ModelManager.java
  src/main/java/taskbook/model/person/Name.java
  src/main/java/taskbook/model/person/Person.java
  src/main/java/taskbook/ui/MainWindow.java
  src/test/java/taskbook/logic/commands/CommandTestUtil.java
  src/test/java/taskbook/logic/commands/ContactDeleteCommandTest.java
  src/test/java/taskbook/logic/commands/ContactSortCommandTest.java
  src/test/java/taskbook/logic/commands/FindCommandTest.java
  src/test/java/taskbook/logic/commands/TaskFindCommandTest.java
  src/test/java/taskbook/logic/commands/modelstubs/ModelStub.java
  src/test/java/taskbook/logic/parser/ContactSortCommandParserTest.java
  src/test/java/taskbook/logic/parser/TaskBookParserTest.java
  src/test/java/taskbook/logic/parser/contacts/ContactCategoryParserTest.java
  src/test/java/taskbook/model/ModelManagerTest.java
Labels: priority.Medium

#174 Add contact find command
  docs/UserGuide.md
  src/main/java/taskbook/logic/commands/categoryless/HelpCommand.java
  src/main/java/taskbook/logic/commands/contacts/ContactFindCommand.java
  src/main/java/taskbook/logic/commands/tasks/TaskFindCommand.java
  src/main/java/taskbook/logic/parser/contacts/ContactCategoryParser.java
  src/main/java/taskbook/logic/parser/contacts/ContactFindCommandParser.java
  src/main/java/taskbook/model/person/Person.java
  src/main/java/taskbook/model/task/Task.java
  src/test/java/taskbook/logic/commands/ContactFindCommandTest.java
  src/test/java/taskbook/logic/commands/TaskFindCommandTest.java
  src/test/java/taskbook/logic/parser/ContactFindCommandParserTest.java
  src/test/java/taskbook/logic/parser/TaskFindCommandParserTest.java
Labels: priority.Medium

#175 Add tags to tasks
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/taskbook/logic/commands/contacts/ContactAddCommand.java
  src/main/java/taskbook/logic/commands/contacts/ContactDeleteCommand.java
  src/main/java/taskbook/logic/commands/contacts/ContactEditCommand.java
  src/main/java/taskbook/logic/commands/tasks/TaskAddCommand.java
  src/main/java/taskbook/logic/commands/tasks/TaskDeadlineCommand.java
  src/main/java/taskbook/logic/commands/tasks/TaskDeleteCommand.java
  src/main/java/taskbook/logic/commands/tasks/TaskEditCommand.java
  src/main/java/taskbook/logic/commands/tasks/TaskEventCommand.java
  src/main/java/taskbook/logic/commands/tasks/TaskTodoCommand.java
  src/main/java/taskbook/logic/parser/CliSyntax.java
  src/main/java/taskbook/logic/parser/tasks/TaskDeadlineCommandParser.java
  src/main/java/taskbook/logic/parser/tasks/TaskEditCommandParser.java
  src/main/java/taskbook/logic/parser/tasks/TaskEventCommandParser.java
  src/main/java/taskbook/logic/parser/tasks/TaskTodoCommandParser.java
  src/main/java/taskbook/model/task/Deadline.java
  src/main/java/taskbook/model/task/EditTaskDescriptor.java
  src/main/java/taskbook/model/task/Event.java
  src/main/java/taskbook/model/task/Task.java
  src/main/java/taskbook/model/task/Todo.java
  src/main/java/taskbook/storage/JsonAdaptedDeadline.java
  src/main/java/taskbook/storage/JsonAdaptedEvent.java
  src/main/java/taskbook/storage/JsonAdaptedPerson.java
  src/main/java/taskbook/storage/JsonAdaptedTask.java
  src/main/java/taskbook/storage/JsonAdaptedTodo.java
  src/test/java/taskbook/logic/commands/TaskTodoCommandTest.java
  src/test/java/taskbook/model/TaskBookTest.java
  src/test/java/taskbook/testutil/DeadlineBuilder.java
  src/test/java/taskbook/testutil/EventBuilder.java
  src/test/java/taskbook/testutil/TodoBuilder.java
Labels: priority.Medium

#180 Update Ui to show task tags
  src/main/java/taskbook/logic/parser/contacts/ContactFindCommandParser.java
  src/main/java/taskbook/ui/PersonListPanel.java
  src/main/java/taskbook/ui/TaskListCard.java
  src/main/java/taskbook/ui/TaskListPanel.java
  src/main/resources/view/TaskListCard.fxml
  src/main/resources/view/TaskListDeadlineCard.fxml
  src/main/resources/view/TaskListEventCard.fxml
  src/main/resources/view/TaskListTodoCard.fxml
Labels: priority.Medium

#181 Fix bug where tags were not parsed for self assigned tasks
  src/main/java/taskbook/logic/parser/tasks/TaskDeadlineCommandParser.java
  src/main/java/taskbook/logic/parser/tasks/TaskEventCommandParser.java
  src/main/java/taskbook/logic/parser/tasks/TaskTodoCommandParser.java
Labels: type.Bug, priority.Medium, severity.High

#182 Update UGDG and the Ui image
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/UiV1.png
Labels: priority.Medium

#183 Update version number
  src/main/java/taskbook/MainApp.java
Labels: priority.High

#184 Edit UG
  docs/UserGuide.md
Labels: type.Bug, priority.Medium

#187 Fix .isSelfAssigned() to check for fullName equality vs object identity
  src/main/java/taskbook/model/task/Task.java
Labels: type.Bug, severity.Medium

#233 Fix edit commands
  src/main/java/taskbook/logic/commands/contacts/ContactEditCommand.java
  src/main/java/taskbook/logic/commands/tasks/TaskEditCommand.java
  src/main/java/taskbook/logic/parser/contacts/ContactEditCommandParser.java
  src/main/java/taskbook/logic/parser/tasks/TaskEditCommandParser.java
  src/main/java/taskbook/model/task/Todo.java
  src/test/java/taskbook/logic/parser/ContactEditCommandParserTest.java
  src/test/java/taskbook/logic/parser/tasks/TaskEditCommandParserTest.java
Labels: type.Bug

#234 Fix bug where non-ascii characters are not removed
  src/main/java/taskbook/logic/parser/TaskBookParser.java
Labels: type.Bug

#232 Fix DateParser parsing of invalid dates
  src/main/java/taskbook/commons/core/Messages.java
  src/main/java/taskbook/logic/parser/DateParser.java
  src/test/java/taskbook/logic/parser/DateParserTest.java
Labels: type.Bug

#235 Update User Guide
  docs/UserGuide.md
Labels: type.Bug

#243 Update Quick Start to include a valid task todo command
  docs/UserGuide.md
Labels: type.Bug, ped.goodtofix
