Repository AY2223S1-CS2103T-T13-4/tp, pull requests merged in 2022-11, with the labels that each got.

#244 NAME case-sensitivity update
  docs/UserGuide.md
Labels: type.Bug, ped.mustfix

#238 Fix User Guide: Adding a contact/task will revert UI from filtered list back to the full list
  docs/UserGuide.md
  src/main/java/taskbook/model/ModelManager.java
Labels: type.Bug, ped.goodtofix

#247 User Guide: Elaborate on criteria for duplicate contacts/tasks
  docs/UserGuide.md
Labels: ped.mustfix

#237 Fix User Guide: Specify full name
  docs/UserGuide.md
Labels: type.Bug, ped.goodtofix

#249 User Guide: Add note for contact delete
  docs/UserGuide.md
Labels: ped.goodtofix

#252 User Guide: Update jar file name
  build.gradle
  docs/UserGuide.md
Labels: type.Bug, ped.mustfix

#250 User Guide: Add note for name parameter
  docs/UserGuide.md
Labels: ped.mustfix

#256 Update UG to explicitly reject country code extensions
  docs/UserGuide.md
Labels: ped.goodtofix

#257 Remove phone number sort
  docs/UserGuide.md
  src/main/java/taskbook/logic/commands/contacts/ContactFindCommand.java
  src/main/java/taskbook/logic/commands/contacts/ContactSortCommand.java
  src/main/java/taskbook/logic/commands/contacts/ContactSortPhoneAscendingCommand.java
  src/main/java/taskbook/logic/commands/contacts/ContactSortPhoneDescendingCommand.java
  src/main/java/taskbook/logic/commands/tasks/TaskFindCommand.java
  src/main/java/taskbook/logic/commands/tasks/TaskSortCommand.java
  src/main/java/taskbook/logic/parser/contacts/ContactSortCommandParser.java
  src/main/java/taskbook/logic/parser/contacts/enums/SortTypes.java
  src/main/java/taskbook/model/person/Person.java
  src/main/java/taskbook/model/person/Phone.java
  src/test/java/taskbook/logic/commands/ContactSortCommandTest.java
  src/test/java/taskbook/logic/parser/ContactSortCommandParserTest.java
Labels: ped.mustfix

#255 Update UG to be more clear about alphabetical sorting
  docs/UserGuide.md
Labels: ped.goodtofix

#261 User Guide: Add constraints for tag
  docs/UserGuide.md
Labels: ped.mustfix

#293 Bug: UG Wrong Command
  docs/UserGuide.md
Labels: type.Bug
